apiVersion: v1
kind: Namespace
metadata:
  name: frontend-team 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: frontend-team
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: httpd
          env:
            - name: DATABASE_URL
              value: "postgres://postgres:postgres@db.default:5432/postgres"
          ports:
            - containerPort: 80
---

apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: frontend-team
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
  type: ClusterIP
